default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: dev_admin
  password: admin
  port: 5433

development:
  <<: *default
  database: ars_dev

test:
  <<: *default
  database: ars_test

production:
  <<: *default
  database: ars_prod
